version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certificat.cer:/etc/nginx/certificat.cer
      - ./nginx/Codesphere_key.key:/etc/nginx/Codesphere_key.key
